#ifndef QTCOLLECTIONS_GLOBAL_H
#define QTCOLLECTIONS_GLOBAL_H

#include <QtCore/QtGlobal>

#ifdef QTCOLLECTIONS_STATIC
#   define QTCOLLECTIONS_EXPORT
#else
#   ifdef QTCOLLECTIONS_LIBRARY
#       define QTCOLLECTIONS_SHARED_EXPORT Q_DECL_EXPORT
#   else
#       define QTCOLLECTIONS_SHARED_EXPORT Q_DECL_IMPORT
#   endif
#endif

#endif // QTCOLLECTIONS_GLOBAL_H
